# Generated by Django 5.1.2 on 2024-10-20 02:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_alter_userprofile_options_follow_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='follow',
            old_name='create_at',
            new_name='created_at',
        ),
    ]
