# Generated by Django 4.2.20 on 2025-04-05 01:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_alter_follow_follower_alter_follow_following'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='follow',
            options={'verbose_name': 'Follower', 'verbose_name_plural': 'Followers'},
        ),
    ]
